<div class="block block-amazon-login">
    <div class="block-title">
        <strong id="block-amazon-login-heading" role="heading" aria-level="2"><?php /* @escapeNotVerified */ echo __('Login with Amazon') ?></strong>
    </div>
    <div class="block-content" aria-labelledby="block-amazon-login-heading">
        <p><?php /* @escapeNotVerified */ echo __('With Amazon Payments, you can use the shipping and payment information stored in your Amazon account to place an order on this website. <br />It\'s a convenient and trusted way to pay that\'s enjoyed by millions of people. By selecting Amazon Payments, you will be asked to sign-in securely to your Amazon account without leaving the shop.') ?></p>
        <div class="actions-toolbar">
            <div class="primary">
                <div class="amazon-button-container">
                    <div class="amazon-button-container__cell">
                        <div id="LoginWithAmazon" class="login-with-amazon" data-mage-init='{"amazonButton": {"buttonType": "LwA"}}'></div>
                    </div>
                    <div class="amazon-button-container__cell">
                        <div class="field-tooltip toggle">
                            <span class="field-tooltip-action action-help" data-mage-init='{"dropdown": {"activeClass": "_active"}}' data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"></span>
                            <div class="field-tooltip-content" data-target="dropdown" aria-hidden="true"><?php /* @escapeNotVerified */  echo __('Securely login into our website using your existing Amazon details.'); ?></div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
